overrides:
  '@babel/helpers@<7.26.10': '>=7.26.10'
  '@eslint/plugin-kit@<0.3.3': '>=0.3.3'
  '@nestjs/common@<10.4.16': '>=10.4.16'
  '@sentry/nestjs@>=8.10.0 <8.49.0': '>=8.49.0'
  '@sentry/node@>=8.10.0 <8.49.0': '>=8.49.0'
  formidable@>=3.1.1-canary.20211030 <3.5.3: '>=3.5.3'
  multer@>=1.4.4-lts.1 <2.0.0: '>=2.0.0'
  multer@>=1.4.4-lts.1 <2.0.1: '>=2.0.1'
  multer@>=1.4.4-lts.1 <2.0.2: '>=2.0.2'
